name: Release
on:
  push:
    branches:
      - main
      - actions
jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies 
        working-directory: .
        run: |
          sudo apt install -y podman qemu-user-static pkg-config
      - name: Build amd64 container
        working-directory: .
        run: |
          podman manifest create betterbell
          podman build --platform linux/amd64 --manifest betterbell .
      - name: Build arm64 container
        working-directory: .
        run: |
          podman build --platform linux/arm64 --manifest betterbell .
      - name: Log in to Github Packages
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to Github Packages
        uses: redhat-actions/push-to-registry@v2
        with:
          image: betterbell
          registry: ghcr.io/l0go
